### ISSUE TITLE
A question about `cleaningY`

### ISSUE THREAD

**Issue by QianhuiWan** [LieberInstitute/jaffelab#6]
Hello, I have a question about `cleaningY` function. Is `cleaningY` function also suitable for removing surrogate variables from DNA methylation array data? I have data from illumina 850K array platform, and I used normalised M value matrix (`Mnorm`) as input data. My code is shown as follows:

```
library(jaffelab)

# model matrix with 5 surrogate variables estimated from comtrol probes
mod <- with(phenoData, model.matrix(~ PC1+PC2+PC3+PC4+PC5))

# regress out 5 surrogate variables from my M value matrix
cleanMnorm <-  cleaningY(y = Mnorm, mod = mod, P = 1)
```

Thank you so much. 

Best regards

Qianhui

**Comment by andrewejaffe** [comment]
Yes, we do that all the time. Note you can transform back the clean data to
the beta scale. You can also apply to the beta scale directly but this
won't ensure resulting cleaned methylation values are between 0 and 1

**Comment by QianhuiWan** [comment]
Thank you so much for your prompt reply to my question, the information was very helpful to me!
